name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install create-elm-app
      run: npm install create-elm-app
    - name: Run tests
      run: ./node_modules/.bin/elm-app test
